// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fftoeynmwxiqevnfweus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdG9leW5td3hpcWV2bmZ3ZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTc4NDQsImV4cCI6MjA2MzY5Mzg0NH0.UUmhQAlBeNJvHy9ELUjKz4PlXSctlIQHiNc5fBs9ZRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);